### ISSUE TITLE
Standardize loading indicator in sassquatch2

### ISSUE THREAD

**Issue by byronhulcher** [meetup/sassquatch2#101]
I'd like to have a standard icon/animation that i can use to indicate loading where I need it.  `static/img/` in our codebase currently has 4 spinners, it would be nice to include the spinner in sassquatch2 so its obvious.  Perhaps a `loading-icon` class I could apply to a div to give it the icon as a background?

In addition, it might be nice to have standardize a way to pop this loader inside an input (We put a loading indicator on the right of the input box sometimes), similar to launcher (http://meetup.github.io/sassquatch2/forms.html#launcher)  Perhaps we could have a selector like `input.input--loading-icon' that when i apply a class to (`loading`/`searching`) it would show the loading indicator?

**Comment by akdetrick** [comment]
@mattkime is working on this in issue #250
