### ISSUE TITLE
create media size between large and extra large

### ISSUE THREAD

**Issue by adrianparsons** [meetup/sassquatch2#102]
Currently media sizes jump from large (72px) straight up to extra large (160px). For Mothership, we created a custom avatar that is 100px in width and height.

**Comment by adrianparsons** [comment]
![screen shot 2015-05-06 at 2 52 22 pm](https://cloud.githubusercontent.com/assets/554784/7501099/d59a498a-f3ff-11e4-9d46-768195133570.png)

**Comment by akdetrick** [comment]
`100px` doesn't fit into our type/media scale, so there are 3 options for this:

1) use `$media-l`
2) use `$media-xl`
3) if this icon absolutely needs to be 100x100, use a page-specific style

cc @rxb @mperrotti 

I'll close the issue, but further discussion is welcome
