### ISSUE TITLE
create rounded-edge avatar modifier

### ISSUE THREAD

**Issue by adrianparsons** [meetup/sassquatch2#103]
For Mothership we created a custom avatar with a 5px border radius. Would be awesome to have this as a standard modifier.

**Comment by adrianparsons** [comment]
![screen shot 2015-05-06 at 2 52 22 pm](https://cloud.githubusercontent.com/assets/554784/7501110/dcad3de0-f3ff-11e4-81c0-4057fc6acd09.png)

**Comment by akdetrick** [comment]
we'll also need to redo avatar sizes....

variant                      | media size 
-------------------------- | ------------------------------------
`avatar--small`          | `$media-xs`
`avatar` (default)      | `$media-s`
`avatar--big`             | `$media-l`
`avatar--huge`          | `$media-xl`

**Comment by akdetrick** [comment]
This is custom to the meetup pro landing pages; closing.
