### ISSUE TITLE
add "uppercase" and other text transform modifiers

### ISSUE THREAD

**Issue by akdetrick** [meetup/sassquatch2#122]

**Comment by byronhulcher** [comment]
The internationalization team prefers that we capitalize copy, rather than relying on css properties (it doesn't work for all languages).  I think adding this as an official selector would end up encouraging people to use the css property.

**Comment by akdetrick** [comment]
good call - i'll flag this in the PR where i found an ad-hoc `.uppercase` class

**Comment by byronhulcher** [comment]
Maybe it would make sense for other text-transforms like underlinine or strikethrough, but for casing specifically I don't think we should go with it.  Thanks Adam!

**Comment by akdetrick** [comment]
going to leave this closed until there's a use case for the other types of text transform
