### ISSUE TITLE
group card hscroll alignment problem

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#127]
in v0.20.0, the `li`s inside `.hscroll-content--cards` don't wrap the body content:
![screen shot 2015-06-18 at 12 15 31 pm](https://cloud.githubusercontent.com/assets/8643567/8221537/fbe84490-15b3-11e5-8f7d-225a5783acc5.png)

This is because `white-space: no-wrap;` is inherited from the parent `.hscroll`.

However, if you add `white-space: normal;` to `.hscroll-content--cards > li`, then the cards get misaligned for long body content:
![screen shot 2015-06-18 at 12 15 07 pm](https://cloud.githubusercontent.com/assets/8643567/8221565/43b877ea-15b4-11e5-889d-cad27120b94b.png)

we need a solution that maintains the `li` alignment while still wrapping card body content

**Comment by mikem-mup** [comment]
`wrap--singleLine--truncate` is an option:

![screen shot 2015-06-18 at 12 29 18 pm](https://cloud.githubusercontent.com/assets/8643567/8221702/ab989e70-15b5-11e5-8e8e-5859b7803912.png)

**Comment by akdetrick** [comment]
allowing text to wrap using `white-space: normal;` on `.card--group-content`; added top vertical align for direct children of `hscroll-content`
