### ISSUE TITLE
FF toggle pill checked state animation jank

### ISSUE THREAD

**Issue by akdetrick** [meetup/sassquatch2#14]
(some flickering and crazy repaints are happening near the end of the animation on check)

![screen shot 2015-02-20 at 11 51 49 am](https://cloud.githubusercontent.com/assets/231252/6305124/ed0a5d92-b8f6-11e4-8bab-63bdf9be51c3.png)

The generated keyframes might be a little bit too heavy-handed for FF. Maybe we can simplify a little bit...

**Comment by mperrotti** [comment]
Fixed by https://github.com/meetup/sassquatch2/commit/4eecff6b7184fe495f1111dfa4c0e0e35faaa1d7
