### ISSUE TITLE
i18n: find out which languages are ok to capitalize/uppercase

### ISSUE THREAD

**Issue by akdetrick** [meetup/sassquatch2#144]
We currently use CSS to force-capitalize and force-uppercase a few things. Let's filter these rules by language as appropriate.

```
sass/core/type/_headings.scss
49:	text-transform: uppercase;
108:	text-transform: none;

sass/ui-components/_rsvpTag.scss
32:	text-transform: capitalize;
```
Use `li8n-only()` and `il8n-exclude()` to filter these rules to the appropriate languages.

**Comment by coraliepachaud** [comment]
Hi. Thanks. It's simple, whenever possible please exclude all non-English languages for any text-transform, it's safer.
Italian: Problem with "I" (the) getting confused with lowercase "L"
German: Uppercase means it's a noun
French: Strict grammatical rules for Lowercase/Uppercase in some category of words
Japanese/Chinese/Korean/Arabic/Hebrew... no concept of lowercase/uppercase
Turkish and some German characters like ß : Letter should becomes different when it's uppercase (different mapping).

Really, to make things simple, just deactivate text-transform for localization :-)

**Comment by akdetrick** [comment]
Thanks!
