### ISSUE TITLE
IE9: item--shrink not shrinking

### ISSUE THREAD

**Issue by sadafie** [meetup/sassquatch2#151]
![screen shot 2015-07-10 at 3 08 31 pm](https://cloud.githubusercontent.com/assets/1033572/8626951/995bb3e8-2715-11e5-8426-b40651d627b9.png)

**Comment by akdetrick** [comment]
Probable solution:

http://codepen.io/akdetrick/pen/jPxKpj

**Comment by akdetrick** [comment]
fixed in `develop` and `master`. 
in release [v0.21.5](https://github.com/meetup/sassquatch2/releases/tag/v0.21.5).
