### ISSUE TITLE
IE11: stack + margin--center not centered

### ISSUE THREAD

**Issue by sadafie** [meetup/sassquatch2#152]
![screen shot 2015-07-13 at 3 20 00 pm](https://cloud.githubusercontent.com/assets/1033572/8658593/dc77bac8-2972-11e5-81ec-a4f74521cde4.png)

on master. https://secure.dev.meetup.com/create/

scroll to bottom. the only page specific styling is:

max-width:616 px on the stack.

**Comment by akdetrick** [comment]
this is a minor gotcha - the `stack` is `display: flex`. The ideal way to center a flex parent is using `align--center` as it not only text-aligns, but sets an `align-self` property for flex parents:

```sass
 38 $_verticalAlign-to-selfAlign: (
 39 `  baseline: baseline,
 40 `  bottom: flex-end,
 41 `  middle: center,
 42 `  top: flex-start
 43 );
 44
 45 @each $alignment in (left, right, center) {
 46 `  @include _modifier(align, $alignment) {
 47 `  `  @include align-self($alignment);
 48 `  `  text-align: $alignment !important;
 49 `  }
 50 }
```

**Comment by akdetrick** [comment]
closing - `align` could mean text align or flex child align... `margin` only means `margin`. Keeping these modifiers as they are.
