### ISSUE TITLE
should .text--error and .text--caption have the same spacing?

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#166]
`.text--caption` is 13px font with no extra spacing:

<img width="366" alt="screen shot 2015-08-11 at 11 14 31 am" src="https://cloud.githubusercontent.com/assets/8643567/9186565/50094a48-401a-11e5-97fc-46a6aa997b7b.png">

`.text--error` is 13px font with `margin-top: 4px;`:

<img width="371" alt="screen shot 2015-08-11 at 11 14 42 am" src="https://cloud.githubusercontent.com/assets/8643567/9186566/538f1634-401a-11e5-9c9c-c609324e0e60.png">

These text modifiers are very similar - maybe we should make the spacing identical so they can be more easily interchanged?

**Comment by mperrotti** [comment]
I see your point @mikem-mup , but .text--caption is often used in more places than just below inputs. would something like:
input + .text--caption,
textarea + .text--caption,
select + .text--caption {
  margin-top: 4px;
}
be too weird/ugly?

**Comment by mikem-mup** [comment]
@mperrotti absolutely - I think the right solution should make sure that "text modifier" classes don't tune the text to only work in a particular place. Currently, `text--error` is tuned to work best below an input, but that's restricting. I think I would recommend adding `margin-bottom: 4px` to `input`s and `textarea`s, and remove the margin from `text--error`. If `text--error` can be used as generally as `text--caption`, we'll have a more predictable, consistent text modifier toolset.

**Comment by byronhulcher** [comment]
+1 to that. I am very much in favor of seperating styling sellectors (colors/fonts/sizes) from layout (floating/positioning/margins).  Sometime you have to be more verbose in the selectors you include on an element, but I think it is worth it in that you get more granularity and increased readability when scrolling through HTML/templates.

**Comment by mikem-mup** [comment]
imma gonna make a PR for this
