### ISSUE TITLE
.item--active - for highlighting selected item in list

### ISSUE THREAD

**Issue by mattkime** [meetup/sassquatch2#167]
proposed code anticipates split view usage

```
@media only screen and (min-width: 640px)
.item--active{
background: #f3f6f9;
font-weight: 700;
}
```

**Comment by akdetrick** [comment]
We should have two versions of this:

`list-item--active` - applies selected state for all viewport sizes...

and some other version for small screens only. `list-item--splitViewActive`?

**Comment by mattkime** [comment]
@mperrotti stated that it should be highlighted only at small sizes....to me it makes more sense for it to be highlighted at all sizes.

**Comment by akdetrick** [comment]
use `list-item--active` styles from chaptstick branch `album_foundation_48917`

**Comment by akdetrick** [comment]
see also: https://github.dev.meetup.com/meetup/meetup/pull/3237/files#diff-48c0b49e935965568ac29d0cfd845a9dR1
