### ISSUE TITLE
Should p tags have 'hyphens: auto' property?

### ISSUE THREAD

**Issue by byronhulcher** [meetup/sassquatch2#168]
We're assigning p tags the 'hyphens:auto' property and w/ related browser-specific prefixes.  On some platforms, like Safari for iOS, 'hyphens: auto' means that there will be hyphens, and that it will break up text. 

I raise this specifically in regards to an issue on our landing page where we had a p tag wrapping text containing the word `Meetup` and the iPhone 5 specifically would break that copy in the middle of `Meet- up` and it was decided this was not 'proper' branding.  Alternatively, maybe we add a `.text--noHyphens` class I could apply to elements?

**Comment by byronhulcher** [comment]
Alternatively `<p>Join a <span class="no-hyphens">Meetup</span>, buddy</p>` but I think that could get mucked with translations.

**Comment by mikem-mup** [comment]
@byronhulcher, you should have push access to this repo to set up a pull request. You can even use GitHub's inline editor and create a PR directly from the code browser - should be simple for a code change this small.

**Comment by byronhulcher** [comment]
Would rather discuss this rather than presuming my suggestion is correct!  I'd be happy to make the PR once I get some buy-in from some of the designers.

**Comment by mikem-mup** [comment]
PRs aren't live code, and can always be closed, so they're perfect for discussion, and are essentially just issues with the proposed (still-modifiable) code attached. When you reach consensus, everyone knows what they're approving, and it's just a button push to merge rather than a discussion-review+code-change+merge...

**Comment by byronhulcher** [comment]
Sounds good. A little different than the process I'm familiar with on other
OSS repos (I was taught opening a PR without discussion first is
presumptuous) but I don't mind, I'll file it tomorrow!
