### ISSUE TITLE
BUG: Back Arrow Alignment Off in Start Flow

### ISSUE THREAD

**Issue by Lippmana** [meetup/sassquatch2#170]
See screenshot.  The back arrow is off kilter int he new start flow.  The issue appears on all platforms but is most noticeable on a phone.

![image](https://cloud.githubusercontent.com/assets/10952826/9316983/a7f03faa-4506-11e5-81d3-63744f05dda8.png)

**Comment by byronhulcher** [comment]
Hey @akdetrick I did some research into this and would like to discuss solutions with you, but they're outside the scope of this repo.

**Comment by akdetrick** [comment]
Looks like it's an issue with our icon handlebars partial in chapstick.

**Comment by akdetrick** [comment]
fixed in: https://bugz.meetup.com/show_bug.cgi?id=49307
