### ISSUE TITLE
.text--error has `margin-top: 4px;` but .text--caption doesn't

### ISSUE THREAD

**Issue by byronhulcher** [meetup/sassquatch2#190]
Seems like these should be the same.  Possible use case, I have a caption for a form field that I would like to change to an error message at a certain length.  Ideally this would not effect the spacing between elements.

**Comment by akdetrick** [comment]
`text--caption` is a general purpose element (see the privacy notice on new group home)

`text-error` is for use in forms.

I think the way to go is to make a `text--formCaption` that extends `text--caption` and adds a margin.

**Comment by akdetrick** [comment]
looks like neither `text--caption` nor `text--error` have a margin top in the latest versions of sq2

**Comment by akdetrick** [comment]
we're good! :+1: :zap:
