### ISSUE TITLE
select box (Android browser)

### ISSUE THREAD

**Issue by unjust** [meetup/sassquatch2#20]
Samsung S3 Mini (White) Android browser

Perhaps this is just how it is, but there is no arrow/affordance for the select box

![screenshot_2015-02-20-16-11-50](https://cloud.githubusercontent.com/assets/92090/6310304/8693ceea-b923-11e4-8325-754d2736bbd9.png)

**Comment by akdetrick** [comment]
Strangely enough, this appears to be default behavior. We're not setting or removing any user agent styles for select inputs... after some more testing, I found the android browser makes every select on the internet look like this (including bootstrap css).
