### ISSUE TITLE
toggle pills hover state sticks around on iOS Safari

### ISSUE THREAD

**Issue by unjust** [meetup/sassquatch2#206]
:hover is made important, and the hover state sticks around for the last pill clicked.
I can override this importance for the topic picker in the meantime.

![image](https://cloud.githubusercontent.com/assets/92090/11350988/30b30c30-9202-11e5-9b41-9d4b5f489d5f.png)

**Comment by unjust** [comment]
Here is the current PR hotfix https://github.dev.meetup.com/meetup/meetup/pull/3704

**Comment by akdetrick** [comment]
fixed in `master`
