### ISSUE TITLE
Checkbox `checked` attribute not working correctly

### ISSUE THREAD

**Issue by mspencermeetup** [meetup/sassquatch2#207]
For example (straight from the docs):
```html
<label for="check2" class="label--switch chunk">
    <input id="check2" class="checkbox" value="blue" type="checkbox" checked />
    Already checked
</label>
```
You can't uncheck this (at least, it's not reflected visually). 

`$('#check2').is(':checked')` will still return the correct value

**Comment by byronhulcher** [comment]
I think its the rules that include `[checked]` as opposed to `:checked` like https://github.com/meetup/sassquatch2/blob/develop/sass/core/forms/_checkbox.scss#L96.  Removing those rules in-browser solved it for me.
