### ISSUE TITLE
basic view test layout (Android browser)

### ISSUE THREAD

**Issue by unjust** [meetup/sassquatch2#21]
Row items different widths, see Windows Phone for screenshot (sorry)

![screenshot_2015-02-20-16-22-06](https://cloud.githubusercontent.com/assets/92090/6310367/16437a90-b924-11e4-99ea-3f40ceb1078d.png)

**Comment by akdetrick** [comment]
looks like `view-head` has some issues as well

**Comment by akdetrick** [comment]
fixed in `master` - looks like the full-view.html test page wasn't applying the `row-item` base class for the `row-item--shrink` elements
