### ISSUE TITLE
i18n override for `h2 { text-transform }` suppresses `.text--headline { text-transform }`

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#216]
[this `.lang-en` modifier](https://github.com/meetup/sassquatch2/blob/develop/sass/core/type/_headings.scss#L50) creates a `text-transform` selector (`.lang-en h2`) that is more specific than `text--headline`, which means that [`text-transform: none`](https://github.com/meetup/sassquatch2/blob/develop/sass/core/type/_headings.scss#L110) is overridden for pages in English

expected: `text-transform: none` should still apply to `h2.text--headline` on English-language pages

**Comment by akdetrick** [comment]
The `uppercase` treatment should be an embellishment for default `h2` styles only; going to fix this by making `.text--headline` _always_ set `text-transform: none`

**Comment by byronhulcher** [comment]
fwiw it has been expressed to me that our translators  prefer that casing be part of the copy, as that makes the intent of the string clearer to translators.  I think ideally we should try to avoid language specific styles in our CSS.

**Comment by akdetrick** [comment]
We'll be updating typographic styles soon using the branding from S&W, which will not include any language-specific text transformations. The `i18n-only` and `i18n-exclude` mixins are currently only used as a fix for foundation styles that proved to be bad ideas in non-English languages.

My idea for the long term is to make those mixins private utilities on which we can build text direction helpers...

```Sass
@mixin textDirection( $direction: "ltr" ) {
     ...
    @include i18n-only([languages using $direction]) {
         @content;
     }
     ...
}
```
