### ISSUE TITLE
Reconcile text alignment for elements with .button class

### ISSUE THREAD

**Issue by byronhulcher** [meetup/sassquatch2#217]
Currently when applying a `.button` class to an `<a>` element and increasing the height, the text will be aligned to the top of the button.

However, when applying a `.button` class to an `<input>` element and increasing the height, the text will be aligned to the center of the button.

These should match, ideally both would vertically center the text.

**Comment by akdetrick** [comment]
buttons with S&W branding will address this issue with flexbox - how urgent is this fix?

**Comment by byronhulcher** [comment]
not urgent, i just used `<form target="{url}" method="get">` works fine for my needs

**Comment by akdetrick** [comment]
leaving this issue open until we finish the S&W-branded UI components

**Comment by akdetrick** [comment]
Rebranded buttons look much better in this regard (using flexbox and more consistent spacing going forward). 

Because this is fixed in `release/2.0.0`, I'm closing this issue.
