### ISSUE TITLE
Reply example (Android browser and IE)

### ISSUE THREAD

**Issue by unjust** [meetup/sassquatch2#22]
The reply example wrapping is a bit off both on Samsung S3 Mini Android browser - see attachment - and Windows 8 Phone IE ( Where it doesnt wrap at all, screenshot stuck in the phone)

![screenshot_2015-02-20-16-30-32](https://cloud.githubusercontent.com/assets/92090/6310388/4f9a0cfa-b924-11e4-8114-ab070e0164de.png)

**Comment by akdetrick** [comment]
fixed in master
