### ISSUE TITLE
Long MUG names overlap view-head on small screens

### ISSUE THREAD

**Issue by mperrotti** [meetup/sassquatch2#228]
Looks like the `padding-top` in `.stripe-heroContent` is getting clobbered by the padding on `.bounds`.
I'd argue that _type.scss isn't the right place for this style anyway, but am open to being told otherwise

![mugnameoverlap](https://cloud.githubusercontent.com/assets/2313998/12130443/55218414-b3d8-11e5-9181-9a4a92ff881e.png)

**Comment by akdetrick** [comment]
Won't fix
