### ISSUE TITLE
simplified pagination

### ISSUE THREAD

**Issue by akdetrick** [meetup/sassquatch2#232]
More info TK - not sure if this should replace existing pagination or become a new component...

mock from @nataliamarmolejo :
![screen shot 2016-01-08 at 2 34 05 pm](https://cloud.githubusercontent.com/assets/231252/12207505/f5fb8586-b614-11e5-9ab0-49acaf6b448d.png)

**Comment by nataliamarmolejo** [comment]
This is the one we are going with:

![pagination_styling](https://cloud.githubusercontent.com/assets/13524560/12272629/7cc3d9d4-b92f-11e5-9f51-33adc225d1eb.png)

**Comment by akdetrick** [comment]
marking chapstick dependency to update current pagination usage:

```
templates/handlebars/account/money/transactions.hbs
templates/handlebars/account/money/transactionsPagination.hbs
templates/handlebars/util/pagination.hbs
templates/mustache/dialogs/photoPicker/photos.mustache
templates/mustache/widgets/pagination.mustache
```

**Comment by akdetrick** [comment]
fixed in `develop`

`3013b94c6678de10654a2bb85d75a62a0cc2f717`
