### ISSUE TITLE
publish sassquatch2 on npm

### ISSUE THREAD

**Issue by mattkime** [meetup/sassquatch2#236]
npm is the future of front end dependency management....i think.

**Comment by byronhulcher** [comment]
Weird to have an npm module that doesn't export anything... You can actually assign tarball links as dependencies here's an example where I did that recently! https://github.com/byronhulcher/tarot-deck/blob/master/package.json#L7  so if we WERE using npm to manage our FE deps we could still include sassquatch2.

**Comment by akdetrick** [comment]
https://www.npmjs.com/package/sassquatch2
