### ISSUE TITLE
Prep for switching to Graphik

### ISSUE THREAD

**Issue by mperrotti** [meetup/sassquatch2#239]
Graphik files live in our Google Drive. Ask @mperrotti or any other designer for the link. 

**Globals:**
 * Font weights (Regular, Medium, Bold)
 * Font sizes

**Defaults:**
 * Tag defaults
 * Text modifier

**Unicode Range:**
 * Basic Latin (0020-007F)
 * Latin-1 Supplement (00A0-00FF)
 * General Punctuation (2000-206F)

This is just step one. After we get Graphik into Sassquatch and working, I want to take some time to do a typographic deep-dive

**Comment by akdetrick** [comment]
pull request against `release/2.0.0` please
