### ISSUE TITLE
Button text turning blue when used in a runningText block

### ISSUE THREAD

**Issue by eilinora** [meetup/sassquatch2#244]
If you have a button that is a link inside of a runningText block the link/button is still turning blue even though it has a button styling attribute. See attached image.

![screen shot 2016-02-09 at 4 10 38 pm](https://cloud.githubusercontent.com/assets/1933722/12961492/b6a670da-d00e-11e5-9c44-6c2ce39edf92.png)

**Comment by akdetrick** [comment]
fixed in `release/1.5.0`
