### ISSUE TITLE
Solution for bullet-separated horizontal list

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#275]
On the topic page, we list topics as text links separated by bullets inside a `inlineblockList`, but because the bullets are part of the item text, the spacing around the bullet gets awkward:

<img width="661" alt="screen shot 2016-03-15 at 12 56 48 pm" src="https://cloud.githubusercontent.com/assets/8643567/13763773/a66a0c54-eaad-11e5-8e7a-be64fab4b7f2.png">

We basically just need to eliminate the `padding-right: 8px` on the `<li>`, but adding `padding--none` is insufficient to override the padding rule selected by `.inlineblockList > li`.

It's not super-broken, but it would be good to decide whether we want to make a fix in SQ2, in chapstick, or in the design (i.e. change the design to use a pattern that is already supported in SQ2)

**Comment by akdetrick** [comment]
Maybe a `middotList` might be a nice useful component?

These list classes are the last bits of SQ2 that use direct child selectors instead of explicit `base-item` classes, which can lead to exactly this kind of problem. I'm not sure if it's worth changing that, or just building a new component if we think we'll use lists like this in the future...

**Comment by mikem-mup** [comment]
> if we think we'll use lists like this in the future

@mperrotti I'd be interested in your preference on this - do you think we'll be listing topics or other things elsewhere on the site? I'm sort of wondering whether we should keep this topic listing identical to the mweb mug home topic listing to keep things consistent.

<img width="443" alt="screen shot 2016-03-18 at 9 24 55 am" src="https://cloud.githubusercontent.com/assets/8643567/13860071/5d082ae2-eceb-11e5-88b7-b81e698f7adf.png">

**Comment by akdetrick** [comment]
Added `text--middotRight` and `text--middotLeft` to `v2.1.0`.

Lists using middots don't seem to be common in the latest design work for redesign, but I do see the pattern in places like:

{group name} (middot) {count} {chapter.who}


https://github.com/meetup/sassquatch2/commit/09059f86515600ef5601e104c67817f68b5a549d
