### ISSUE TITLE
Modify the largest avatar size down from 160px to 120px

### ISSUE THREAD

**Issue by tgtg** [meetup/sassquatch2#281]
The current `avatar--big` class is too big – let's lower it to 120px to create a more manageable size and better scale relation to the smaller sizes.

**Comment by akdetrick** [comment]
waiting for `release/2.0.0` to merge fix

**Comment by akdetrick** [comment]
fixed in `master`

**Comment by akdetrick** [comment]
https://github.com/meetup/sassquatch2/commit/5957fa2c46d3b059f31c5d0ff411753856dd4920

The fix is in `release/2.1.0`. The release branch/tag will be merged to master once chapstick/bugzilla bug #52295 is launched.
