### ISSUE TITLE
Web replatform/redesign style needs

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#287]
I'm opening this issue just to have a central place to put style requests for the web replatform as we go along.
- [x] libsass compilation support - we will probably channel everything through Webpack with [sass-loader](https://github.com/jtangelder/sass-loader)
  - I am eager to help with this

**A few things for event cards**

![image](https://cloud.githubusercontent.com/assets/2313998/14121084/ead806c2-f5c3-11e5-8cb6-2f7b47c8e3a0.png)
- [ ] green-shaded buttons for "I'm going" indicator
- [ ] white-on-black button that is not in an `.inverted` context for the 'waitlisted' button
- [ ] a way to tighten the line-height for the `<h5>` event name, which will frequently wrap to two lines at mobile widths

**Comment by akdetrick** [comment]
`attachment` may help with compact spacing in the recurring event list: http://meetup.github.io/sassquatch2/ui_components.html#attachment

**Comment by akdetrick** [comment]
Requests here are either out of date or completed. Future updates to support styling on the new platform will be in either [`swarm-sasstools`](https://github.com/meetup/swarm-sasstools) or [`meetup-web-components`](https://github.com/meetup/meetup-web-components)
