### ISSUE TITLE
Inverted and SVGs

### ISSUE THREAD

**Issue by eilinora** [meetup/sassquatch2#297]
If an SVG is inside of div that is set to inverted, it unfortunately does not get set to a fill of white.

Example:
![screen shot 2016-06-10 at 10 36 09 am](https://cloud.githubusercontent.com/assets/1933722/15967813/2c5e1f84-2ef7-11e6-81bc-d531ad394e5b.png)

**Comment by akdetrick** [comment]
for chapstick, we handle this in `static/style/foundation/components/_icons.scss:6` with ` @mixin _iconColor( $color, $invertedColor )`

It makes sense to set a global default for the `fill` property in SQ, though...
