### ISSUE TITLE
kerning looks off with small heavy text in FF42 / linux 

### ISSUE THREAD

**Issue by akdetrick** [meetup/sassquatch2#299]
This might be something we should take a look at in general; do we want to kern small heavy text, or force `letter-spacing` to `normal`?

https://meetuphq.slack.com/files/anne/F1GF6760Z/find_reskin.png

**Comment by anne-meetup** [comment]
so you know: kerning still looks off on firefox 47/ubuntu 14.04 but in the process of upgrading I accidentally changed a bunch of my other fonts for the worse so it looks better comparatively?
