### ISSUE TITLE
Merge `flex--align[Direction]` with `valign--[direction]`

### ISSUE THREAD

**Issue by mperrotti** [meetup/sassquatch2#310]
Needed for replatform work. The `<Flex>` component renders alignment classes with the `align` prop, but we don't need two sets of classes that do the same thing.

via: https://github.com/meetup/meetup-web-components/pull/23

**Comment by akdetrick** [comment]
Going to close this. This is to support the `<Flex`react component, so the CSS should live in `meetup-web-components`
