### ISSUE TITLE
Should --spread properties only apply to first children?

### ISSUE THREAD

**Issue by byronhulcher** [meetup/sassquatch2#41]
Consider the following hypothetical:
```
<div class="stack atLarge_stack--spread">
    <div class="stack-item">
        <div class="stack">
            <div class="stack-item chunk">
                A: This should always be on top B
            </div>
            <div class="stack-item chunk">
                B: This should always be below A 
            </div>
        </div>
    </div>
    <div class="stack-item chunk">
        C: This should be to the right of A&B at large, otherwise below
    </div>
    <div class="stack-item chunk">
        D: This should be to the right of C at large, otherwise below
    </div>
</div>
```

I would want `.stack .stack` element, which I have not included a --spread class with, to always have its child `.stack-item`s be stacked and never spread out. However at large screen sizes, the `.stack.atLarge_stack--spread` css property is being also applied to `.stack .stack .stack-item`

**Comment by akdetrick** [comment]
In this example, the nested `stack` isn't necessary if there are no conditional changes; any block-level element works fine without creating a `stack`.

But yeah, we will want to nest a stack at some point, so I'll fix the direct child selection issue (same for gridlist).
