### ISSUE TITLE
`.hasJS .menu-actions` can't be made visible with `display--block`

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#55]
this two-selector `display:none` rule overrides `.display--block` https://github.com/meetup/sassquatch2/blob/develop/sass/ui-components/_menu.scss#L47

The recommended solution is to *remove* the `display:none` rule and use `hasJS_display--none` as a modifier - we could do this with an @extend inside `.menu-actions` instead of requiring it in the markup, but the markup option is also fine.

**Comment by akdetrick** [comment]
fixed in `master`
