### ISSUE TITLE
Spacing issues in .attachment children

### ISSUE THREAD

**Issue by mperrotti** [meetup/sassquatch2#65]
Chunk
.chunk should have margin-bottom set to $space-half, but it stays at $space because it's clobbered by the !important declaration in sass/core/layout/_chunk.scss
![screen shot 2015-03-31 at 10 33 53 am](https://cloud.githubusercontent.com/assets/2313998/6921333/3ab251a8-d792-11e4-8314-dacc3aec9128.png)

First-child row-items
.row-item:first-child should have padding-left set to $space-half, but it's clobbered by the padding-left set in sass/ui-components/_attachment.scss
![screen shot 2015-03-31 at 10 34 42 am](https://cloud.githubusercontent.com/assets/2313998/6921337/40118998-d792-11e4-8422-8676a8438f85.png)

**Comment by akdetrick** [comment]
in an `!important` war, nobody wins
