### ISSUE TITLE
Should docs/* be gitignored?

### ISSUE THREAD

**Issue by sjhcockrell** [meetup/sassquatch2#94]
Since it's a generated resource, is it worth adding the following line to the .gitignore?

```gitignore
docs/*
```

**Comment by akdetrick** [comment]
The generated files live in `docs/build/`, and yes, should be gitignored. We currently have a somewhat broken process for pushing documentation to gh-pages via a grunt plugin which requires that the built docs be checked in.

This was supposed to be a temporary measure; I haven't had time to fix this yet, but a bug is already open to address this https://github.com/meetup/sassquatch2/issues/78

Going to mark this closed (dupe of https://github.com/meetup/sassquatch2/issues/78)
