### ISSUE TITLE
icon alignment is not great on borderless buttons with icons

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#97]
![screen shot 2015-04-30 at 7 59 41 am](https://cloud.githubusercontent.com/assets/8643567/7400166/0be237b4-ef0f-11e4-9920-f695d8e1baac.png)

I think this is an issue on regular buttons with icons as well - the text baseline doesn't line up with the icon baseline.

**Comment by akdetrick** [comment]
addressing this in chapstick 
https://trello.com/c/knDr40aa
